twali-xyz-staging:
  component: "@sls-next/serverless-component@3.7.0-alpha.11"
  inputs:
    roleArn: "arn:aws:iam::517934542124:role/deploy-dev"
    build:
      env:
        TABLE_NAME: "Twali-core-test"
        CONTRACT_BUCKET: "twali-contracts-bucket"
        WHITELIST_TABLE: "whitelist_table"
    cloudfront:
      distributionId: EHZYCKLX3TYQ4 # for Staging env only, change for local testing
    bucketName: qdlwzqy-k2v6lc # for Staging env only, change for local testing
