twali-xyz-staging:
  component: "@sls-next/serverless-component@3.7.0-alpha.11"
  inputs:
    roleArn: "arn:aws:iam::517934542124:role/deploy-dev"
    build:
      env:
        TABLE_NAME: "dev_staging_user_profile_test"
    cloudfront:
      distributionId: EHZYCKLX3TYQ4
    bucketName: pxn4tf-zy2dp9