#
# Staging enviroment deployment 
#

name: deploy stagging-twali

on:
  push:
    branches: [stagging]
  pull_request:
    branches: [stagging]

jobs:
  deploy-stagging:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Configure AWS Credntials
          uses: aws-actions/configure-aws-creditals@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - uses: canastro/copy-file-action@master
          with:
            source: "severless-staging.yml"
            target: "severless.yml"

        - uses: actions/setup-node@v2-beta
          with:
            node-version: "16.x"
          
        - name: Install dependencies
          run: npm ci 

        - name: Deploy to staging-twali AWS enviroment
          run: serverless
